# Site settings
title: Hugo Lhuillier
email: hugo.lhuillier@princeton.edu

# Sidebar settings
description: Hugo Lhuillier

# Social icons
# google_scholar: fMPIb8sAAAAJ
# linkedin: gregory-owens-34434b100
github: HugoLhuillier
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hugolhuillier.github.io/" # the base hostname & protocol for your site


footer: Hugo Lhuillier <br>

        Department of Economics <br>

        Julis Romo Rabinowitz Building <br>

        Princeton, NJ 08544

# Build settings
markdown: kramdown

highlighter: rouge

plugins:
  - jekyll-sitemap

collections:
  visualization:
    output: true
    permalink: /visualization/:path/
